import MainHeader from 'src/comps/header/MainHeader';
import './global.css'
import 'bootstrap/dist/css/bootstrap.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      
      <body>
          <div className="container-fluid">
            <MainHeader/>
            {children}
          </div>
      </body>
    </html>
  )
}
